print('What is the name of the city you grew up in \n' )
city = input("")
print(city)
print("what is the name of the pet's name")
pet = input("")
print('Your band name is could be' + " " + city + " " + pet)
